idf_component_register(
    SRCS
        "main.cpp"
        "ros_app.cpp"
        "led_manager.cpp"
        "otos_node.cpp"
        "can_driver.c"
        "can_rx_dispatch.c"
       
        "homing_node.c"
        "servo.c"
        "phase_node.c"
        "esp32_serial_transport.c"
        "led_strip_encoder.c"
    INCLUDE_DIRS
        "."
        "../include"
    REQUIRES
        micro_ros_espidf_component
)
